### ISSUE TITLE
fontawesome icons support?

### ISSUE THREAD

**Issue by Dieterbe** [phinze/mermaid-docker#2]
hey Paul,
thanks for making a docker image so I don't have to mess with npm on my system ;-)
I noticed fontawesome icons don't work though.
according to the docs (https://mermaidjs.github.io/flowchart.html), this should work:
```
$ cat test.md
graph TD
    B["fa:fa-twitter for peace"]
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner);
    B-->E(A fa:fa-camera-retro perhaps?);
```
But when I run:
```
docker run -v $(pwd):/data phinze/mermaid test.md
```
I get this output:
![test md](https://user-images.githubusercontent.com/20774/52669639-d7557a00-2f16-11e9-96a6-305f93c70edc.png)

I've been trying to rebuild the docker image using a slightly newer version of mermaid, changing the npm install command to either of 
```
npm install -g d3@4.13.0 mermaid@8.0.0 phantomjs-prebuilt@2.1.16 --unsafe-perm && npm cache clean --force
npm install -g mermaid@8.0.0 phantomjs-prebuilt@2.1.16 --unsafe-perm && npm cache clean --force
```

but both result in `npm WARN dagre-d3-renderer@0.5.8 requires a peer of d3@^4.13.0 but none is installed. You must install peer dependencies yourself.` and the `mermaid` command not being found when i run the container.

actually, rebuilding the docker image from the Dockerfile in this repo also results in the `mermaid` command not being found.
i found out the https://hub.docker.com/r/phinze/mermaid/dockerfile is different than in this repo, trying to use that one resulted in some errors that i could fix by adding `--unsafe-perm` and `--force` to the 2 commands respectively. but that one results in the `mermaid` command not being found as well :/

**Comment by Dieterbe** [comment]
oh the mermaid command not being found anymore seems due to it being moved into a separate project https://mermaidjs.github.io/mermaidCLI.html
never mind that i also got this error when i tried the exact same dockerfile (and hence mermaidjs version) as what was in this repo. and couldn't find a changelog upstream either...

made some progress:
```
FROM node:latest
RUN npm install -g mermaid@8.0.0 mermaid.cli phantomjs-prebuilt@2.1.16 --unsafe-perm && npm cache clean --force
WORKDIR /data
ENTRYPOINT ["mmdc"]
CMD ["--help"]
```
but this breaks when trying to run:
```
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer/.local-chromium/linux-624492/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/Launcher.js:360:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/mermaid.cli/node_modules/puppeteer/lib/Launcher.js:349:50)
    at Interface.emit (events.js:202:15)
    at Interface.close (readline.js:395:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
